import type { Metadata } from "next";

import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css"
import AuthProvider from "@/context/AuthProvider";


export const metadata: Metadata = {
  title: "Exam-online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
